
def raise_error(error):
  raise Exception(error)
